### ISSUE TITLE
Modrinth page

### ISSUE THREAD

**Issue by DeepVoidLegend** [Numelon-Softworks/ThreatenGL#14]
why u delete mod page on modrinth?

**Comment by Richy-Z** [comment]
I didn’t, and I’m not entirely sure about what happened. Didn’t get any emails or anything lol.
I’ll try and sort this out.

**Comment by xboct02** [comment]
It looks like someone didn't like humor.

**Comment by Richy-Z** [comment]
huh?

**Comment by Richy-Z** [comment]
@Rad586 
LGPLv3 😊

**Comment by Rad586** [comment]
> @Rad586 LGPLv3 😊

Thanks for replying! It would be highly appreciated if you add a `License` at the root of the project!
I was creating a modpack on curseforge, which requires "non-curseforge mod" to be in Approved Non-CurseForge Mods, which needs "a page that clearly displays the license used by the mod". This mod brings explosive client fps boost, it would be amazing to see this mod in modpacks of curseforge!
https://www.gnu.org/licenses/lgpl-3.0.en.html#license-text

**Comment by Richy-Z** [comment]
Hey @Rad586, I've added the COPYING.LESSER file (the license file for the LGPL v3.0 License) as per your request.

**Comment by DesolateIntention** [comment]
Any updates? Why was it removed?

**Comment by Richy-Z** [comment]
It was not fully deleted, but rather temporarily moderated and placed on review by the Modrinth moderation team for "misleading users" 💀 Personally I think that both the Modrinth description and the GitHub description are clear enough and evidently state that this mod will NOT guarantee significant performance improvements, and that this is an experimental mod which simply aims to test how OpenGL profiles work. That being said, I completely understand how a moderator could potentially skimp over the smaller details of this mod as they probably look at thousands of mods on a daily basis. One unusual thing to note here however is the fact that if this mod was only moderated a few weeks ago, then how come it stayed up after literally being ***approved*** initially? That literally means that when I first submitted this mod to Modrinth, a human looked at the mod, the description and the code, and thought to themselves: "yep its all good 👍" and made it live on Modrinth. I wont mention any specific names here, but there is no doubt that some people reported this mod for being "useless" after I initially pitched it in a mysterious Discord server... 😆

**Comment by Richy-Z** [comment]
I am incredibly busy this week and will not have the time to fully resolve all issues immediately. Next week does free up a bit though so I will definitely put it in my to-do list. Thank you for all the continued support on GitHub even after the mod being taken down!

**Comment by xboct02** [comment]
To be honest, the moderators caught up with my idea about the need for a mod with the existing 4.6

**Comment by Richy-Z** [comment]
Hey all!
After a slight pause in development because of lack of time and the mod being removed from Modrinth, people in the Numelon discord server have voted to continue development on this mod and get it back on Modrinth.

**Comment by Richy-Z** [comment]
The mod has been appealed and is waiting for approval from the Modrinth moderators.
Sorry for the incredibly long wait! 😓

**Comment by Richy-Z** [comment]
The mod is now back on Modrinth! Thank you, everyone, for all of your support in this.
I will close this issue now 🤗
