### ISSUE TITLE
Game crashed when click this mod in Forge mod list

### ISSUE THREAD

**Issue by KigeYark** [Numelon-Softworks/ThreatenGL#5]
- ThreatenGL worked as expectation (Confirmed by using Better F3)
- Game won't crash when click other mods
 
### Game Version
Minecraft 1.19.2 with Forge 43.3.13

### Mods
- Architectury 6.6.92
- ThreatenGL 1.2.1-beta.2

### Logs
- [latest.log](https://github.com/Numelon-Softworks/ThreatenGL/files/15329781/latest.log)
- [crash-2024-05-16_12.49.36-client.txt](https://github.com/Numelon-Softworks/ThreatenGL/files/15329783/crash-2024-05-16_12.49.36-client.txt)

### Reproduction (GIF)
![2024-05-16_12-56-55](https://github.com/Numelon-Softworks/ThreatenGL/assets/58782476/7a991b26-eaa1-4148-ab1a-974165874e70)

**Comment by Richy-Z** [comment]
Thank you for being incredibly comprehensive with this issue - it has allowed me to resolve the issue swiftly. :)
A new release will be live on GitHub and Modrinth soon which fixes the crash.

**Comment by Richy-Z** [comment]
The issue has been fixed in ThreatenGL 1.2.1-beta.3, which is available now:
**Modrinth (Recommended)**: https://modrinth.com/mod/threatengl/versions
**GitHub**: https://github.com/Numelon-Softworks/ThreatenGL/releases/tag/1.2.1
